name: Build Sing-Box GUI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 手动触发工作流
  release:
    types: [ created ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 更新到最新版本
    
    - name: Set up Go
      uses: actions/setup-go@v5  # 更新到最新版本
      with:
        go-version: '1.21'  # 使用最新稳定版本
        cache: false
    
    - name: Install Dependencies
      run: |
        go mod tidy
        go get -u fyne.io/fyne/v2
        go get -u github.com/go-gl/gl
        go get -u github.com/go-gl/glfw
    
    - name: Build Windows Executable
      run: |
        $env:CGO_ENABLED=1
        go build -ldflags "-H windowsgui" -o singbox-gui.exe
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # 更新到最新版本
      with:
        name: singbox-gui-windows
        path: singbox-gui.exe
        retention-days: 30  # 保留工件30天
    
    - name: Create Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./singbox-gui.exe
        asset_name: singbox-gui-windows-amd64.exe
        asset_content_type: application/octet-stream 